// <auto-generated />
namespace CaseStudy2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addmenuItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmenuItem));
        
        string IMigrationMetadata.Id
        {
            get { return "202004170641484_addmenuItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
